### ISSUE TITLE
Error while sending a message on console.

### ISSUE THREAD

**Issue by parasharrajat** [Expensify/Expensify.cash#1385] opened 2021-02-02 04:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  Web - v1.0.1-403 

**Action Performed (reproducible steps):** 
Send a message on the report and check the console. 

**Expected Result:** 

There should be no errors and the message should update in the ONYX store.

**Actual Result:**
Getting an error on the logs which is failing update to the Onyx store.

**Notes/Photos/Videos:** 
Web
```
Uncaught (in promise) TypeError: can't access property "sequenceNumber", reportAction is undefined
    updateReportWithNewAction Report.js:244
    addAction Report.js:639
    promise callback*addAction Report.js:639
    onSubmit ReportView.js:52
    submitForm ReportActionCompose.js:139
    triggerSubmitShortcut ReportActionCompose.js:118
    handleKeyDown index.js:306
    React 44
    sendDataToConnection Onyx.js:246
    connect Onyx.js:312
    promise callback*connect/</< Onyx.js:312
    each Underscore
    connect Onyx.js:311
    promise callback*connect Onyx.js:288
    connectMappingToOnyx withOnyx.js:129
Report.js:244:33
    updateReportWithNewAction Report.js:244
    addAction Report.js:639
    (Async: promise callback)
    addAction Report.js:639
    onSubmit ReportView.js:52
    submitForm ReportActionCompose.js:139
    submitForm self-hosted:1176
    submitForm self-hosted:1176
    triggerSubmitShortcut ReportActionCompose.js:118
    triggerSubmitShortcut self-hosted:1176
    handleKeyDown index.js:306
    React 17
    bind_applyFunctionN self-hosted:1374
    dispatchEvent self-hosted:1337
    React 5
    bind_applyFunctionN self-hosted:1374
    dispatchDiscreteEvent self-hosted:1337
    React 14
    performSyncWorkOnRoot self-hosted:1223
    React 8
    sendDataToConnection Onyx.js:246
    connect Onyx.js:312
    (Async: promise callback)
    connect Onyx.js:312
    each Underscore
    connect Onyx.js:311
    (Async: promise callback)
    connect Onyx.js:288
    connectMappingToOnyx withOnyx.js:129
```

**Comment by marcaaron** [comment] 2021-02-17 23:32
Hey @parasharrajat thanks for creating this issue. Just a heads up we will need a reproduction in order to get it prioritized and assigned. Do you know what you did to make this happen?

**Comment by parasharrajat** [comment] 2021-02-18 17:28
I think it's a serious issue. So I have recorded a video. Let me know What I can do to help you reproduce this.
#### Browsers
Chrome, Firefox.

https://user-images.githubusercontent.com/24370807/108396250-a6faf180-723c-11eb-937d-fe15f1b6b4bf.mp4

**Comment by marcaaron** [comment] 2021-02-18 17:42
Ah thanks for the video. We are actually aware of this issue and it must be fixed on the API side (so the issue is not fixable in the front end). It's specific to group chats with "Concierge" as a participant. For single participant chats you'll maybe see this doesn't happen.

**Closed by marcaaron** 2021-02-18 17:42 UTC
