### ISSUE TITLE
Expensify.cash - Can't see chat list beneath request money flow, can't close Modal 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/Expensify.cash#2402] opened 2021-04-14 23:18 UTC
[Upwork issue](https://github.com/Expensify/Expensify.cash/issues/2402#issue-858335205)
__

**Goal**: Work out why https://expensify.cash/iou/split works as expected, while https://expensify.cash/iou/request does not and fix accordingly

## Expected Result:
When launching the IOU Request money flow via the URL route https://expensify.cash/iou/request, chat list should show beneath and you should be able to close the Modal.

## Actual Result:
When launching the IOU Request money flow via the URL route https://expensify.cash/iou/request, the Modal is displayed on top of a grey screen and the modal can't be closed:
![114549110-83f72780-9c58-11eb-95a5-775dd8aa7182](https://user-images.githubusercontent.com/36425901/114791893-1d4b3a00-9d3c-11eb-9c90-6f2bf4ee7926.png)

## Action Performed:
1. Open the IOU money flow request via the URL route https://expensify.cash/iou/request
2. Attempt to close the modal and view chat list

## Platform:
Where is this issue occurring? Web 

## More Context:

Interestingly, https://expensify.cash/iou/split works as expected:

<img width="1295" alt="Screen Shot 2021-04-14 at 11 54 13 AM" src="https://user-images.githubusercontent.com/36425901/114792560-736cad00-9d3d-11eb-8f6f-55e38484ec20.png">

Expensify/Expensify repo [issue](https://github.com/Expensify/Expensify/issues/160218).

**Comment by tugbadogan** [comment] 2021-04-15 17:31
This issue is not reproducible anymore. It looks like it was fixed by @marcaaron in https://github.com/Expensify/Expensify.cash/pull/2399

Staging is working as expected

https://staging.expensify.cash/iou/request
https://staging.expensify.cash/iou/split

**Comment by Julesssss** [comment] 2021-04-21 10:02
Thanks for letting us know @tugbadogan, we'll add add a small bonus to the Preview issue payout.

**Closed** 2021-04-21 10:02 UTC
Labels: Exported
