### ISSUE TITLE
Add GSD mode to reprioritize Sidebar results

### ISSUE THREAD

**Issue by marcaaron** [Expensify/Expensify.cash#1452] opened 2021-02-10 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Deliverables:** 

- Add a new user preference in `SettingsPage` that will allow the user to set a priority preferences for the "Chats" screen (a.k.a. sidebar) it will have two different modes: "GSD" (value `gsd`) and "Most Recent" (value `default`).

<img width="373" alt="Screen Shot 2021-02-10 at 10 48 51 AM" src="https://user-images.githubusercontent.com/32969087/107570474-a5229580-6b8d-11eb-91b1-9bb58a7db5dc.png">

- This will require implementing the `react-native-picker` library and testing that it works on all platforms:
https://github.com/react-native-picker/picker

- We must also modify [this method](https://github.com/Expensify/Expensify.cash/blob/6971def8f61da3d9d5b9f0ac806bfef2c2d820d9/src/libs/OptionsListUtils.js#L374-L382) so that the logic changes as following when someone has selected `gsd` mode:
    - Pinned reports still display but they are no longer prioritized in any particular order (e.g. moved to the top)
    - Reports that have been read will no longer display in the list and should drop out of the list once they are read (and not the active report)
    - Results will be sorted in alphabetical order

**Note:** This should _only_ affect the sidebar and **not** other methods using the [`getOptions()`](https://github.com/Expensify/Expensify.cash/blob/6971def8f61da3d9d5b9f0ac806bfef2c2d820d9/src/libs/OptionsListUtils.js#L151) method here.

- Changing this mode should result in an immediate refresh of the sidebar and will also be persisted in the server so making an API call will be necessary.

**[Upwork Job](https://www.upwork.com/jobs/~01b01001662f67d2ef)**

**Comment by trjExpensify** [comment] 2021-02-10 22:42
Let's go with this copy for now for GSD mode:

This will only display unread and pinned chats, all sorted alphabetically.  _Get Shit Done_.

**Comment by marcaaron** [comment] 2021-02-16 04:08
Taking this one off hold now as the nvp changes have been added.

**Comment by arielgreen** [comment] 2021-02-16 18:17
Posted to [Upwork](https://www.upwork.com/jobs/~01b01001662f67d2ef).

**Comment by tugbadogan** [comment] 2021-02-18 00:34
Hi @marcaaron @arielgreen ,

I would like to work on this issue. Here is my proposal:

I'm planning to add picker view above `Sign Out` button here.
https://github.com/Expensify/Expensify.cash/blob/4d15b34115bae14fe14fa46aa3e93ea9ff8726c3/src/pages/SettingsPage.js#L80-L87

I found that you’ve already implemented the function to call the API method for storing user preference in the server. When user changes the preferences, I will call this function.
https://github.com/Expensify/Expensify.cash/blob/9da0f7746726914ee73692df6d264e771493c12f/src/libs/actions/Account.js#L11-L14

There is also function for fetching this preference from the server and send it to Onyx.
https://github.com/Expensify/Expensify.cash/blob/9da0f7746726914ee73692df6d264e771493c12f/src/libs/actions/Account.js#L19-L28

And it’s called here:
https://github.com/Expensify/Expensify.cash/blob/d8c27d383c47990716539bd4d0bbbf149f104a67/src/pages/home/HomePage.js#L98

I need to pass another boolean parameter that shows whether gsd mode is enabled or not to `getOptions()` function. I can get chat order preference from Onyx in `getSidebarOptions()` function right before calling `getOptions()` function.
https://github.com/Expensify/Expensify.cash/blob/6971def8f61da3d9d5b9f0ac806bfef2c2d820d9/src/libs/OptionsListUtils.js#L374-L382

In `getOptions()` function, I will hide reports (including pinned reports) that have been read and sort all unread reports in alphabetical order.
https://github.com/Expensify/Expensify.cash/blob/6971def8f61da3d9d5b9f0ac806bfef2c2d820d9/src/libs/OptionsListUtils.js#L151

**Comment by anthony-hull** [comment] 2021-02-18 13:07
I will first update the settings page to include the picker component. I will then initially test it working on iOS, Android, Web and Desktop.

I will then send the updated preference to Onyx and and the backend verify this is changing in Local Storage. I will check it persists via clearing the local storage and logging back in and checking the key.

I will then add the ONYXKEYS.PRIORITY_MODE to the export of the SidebarLinks to bring the preference key into the HOC state and the wrapped components props. I will then verify this value is being changed.

I will then start the logic of changing the filtering and ordering of the reports.

First I will refactor the tests for getSidebarOptions OptionsListUtilsTest.js  to handle this new case as the current test assumes pinned will be sorted. I will add a parameter for passing in the value of `ONYXKEYS.PRIORITY_MODE`. I will make a ENUM CONST for the string values of this key. I will use this const in the tests, implementation and for the picker component.

Based on the value of 'default' or 'getShitDone' 😆  passed to getSidebarOptions I will change the parameters passed to getOptions such as prioritizePinnedReports. 

My first thought is to make a new parameter of show only unread reports and default this to false so that other functions that don't know about that parameter aren't affected. I will then test a few features that rely on the getOptions function to test for regression.
Also add another parameter for sort alphabetically.
The idea is to make these options re-useable as these are utility functions. 

I will think more on when I get to those parameters.

I will implement the logic of the sorting and filter options I add before returning the recentReportOptions.

On the way I will update the relevancy documentation comments and prop types.

This is how I imagine it working without actually working with the code and validating assumptions on how this works :)

### Questions:
I can see there is already:
sortByLastMessageTimestamp
If I add another sort function and later both are enabled it might have some unintended side effects without looking into how the lodash sort works. I can do so but I would rather some input before I go down that route.

What would you like done about that? Possibly change to use a more general sort prop ENUM and refactor the implementations of sortByLastMessageTimestamp to use it we could ensure only one filter is applied?

Is `ONYXKEYS.PRIORITY_MODE` the ONXY key you want used for this?





There is a concept of recent reports, if you're sorting alphabetically, they might not be recent? 


### Assumptions

I've not worked in Onxy before, I'm assuming adding the key to the exports of the HOC wrap will be enough to subscribe to changes in the store and change the state of the HOC and the props of the presentational component and hence trigger a re-render of the chat list. 

I'm assuming network issues are handled elsewhere and I don't need to have any error handling of using the updatePriorityMode

**Comment by marcaaron** [comment] 2021-02-18 17:27
@tugbadogan Thanks for the proposal. It looks great, but we have a few issues assigned to you already so going to give @anthony-hull a crack at this :)

@anthony-hull Thanks for the notes, I'll address your questions now.

>If I add another sort function and later both are enabled it might have some unintended side effects without looking into how the lodash sort works. I can do so but I would rather some input before I go down that route.

If we are applying an alphabetical sort then we really don't need to bother with the existing sorting options. We could go the route of an enum, but keep in mind that we are sorting by last message or last accessed _before_ pinned chats since the pinned chats are prepended _after_ we sort. If we want `gsd` mode to just alphabetize all results then there is no need to perform an initial sort at all. 

So, as long as we do time based sorting before pinned reports and alphabetic sorting after it doesn't really matter whether we use a new option `sortAlphabetical` or a `sortOrder` enum. Personally, I think you will have less changes if you stick with `sortAlphabetical` and since this code is still in it's infancy we can avoid any refactors.

>Is ONYXKEYS.PRIORITY_MODE the ONXY key you want used for this?

yep

>There is a concept of recent reports, if you're sorting alphabetically, they might not be recent?

"Recent reports" in the case of `OptionsListUtils` just refer to all reports that may need your attention. Said another way, if `includeRecentReports` is false then we are not showing any report options at all.

>I've not worked in Onxy before, I'm assuming adding the key to the exports of the HOC wrap will be enough to subscribe to changes in the store and change the state of the HOC and the props of the presentational component and hence trigger a re-render of the chat list

Yep, a component wrapped in `withOnyx` will update when a prop it subscribes to changes.

>I'm assuming network issues are handled elsewhere and I don't need to have any error handling of using the updatePriorityMode

We don't have any specific requirement for handling errors related to calling this API right now. But the priority mode should be updated "optimistically" so that it's set in `AsyncStorage` and then the API call makes an attempt to persist. If the API fails then we'll use whatever value is in storage. It just would not be sync'd across devices.

**Comment by anthony-hull** [comment] 2021-02-20 16:38
Do you wish this to change the setting onChange or to have a save button?
Do you want any kind of feedback to the user that it has saved?
If you want a save button, what do you want to happen if the user tries to close the settings page without saving changes?

**Comment by anthony-hull** [comment] 2021-02-21 17:27
I have completed the logic and (almost all) styling on the web and android version based of the assumption you want the key updated onValueChange.

I ran into an issue with iOS that the picker library takes up a lot more space than in the designs and works differently to s drop down. Please look on the project page at the iOS and PickerIOS screenshots.


I found an alternative:
https://github.com/lawnstarter/react-native-picker-select
which wraps the RN team's picker library in a modal and gives you freedom to style the elements in the page. This would allow the styling and layout of the settings page to be more consistent across platforms. (it is also more popular)

I ran into webpack/loader/babel issues when trying it out. 

I would like input on what you want done before continuing.

**Comment by shawnborton** [comment] 2021-02-22 08:00
> By this do you mean to change the setting on changing the selection of the dropdown?
> or to have a save button and then immediately refresh the sidebar?

For now, I think it's okay if we just save as soon as the dropdown is changed. No need for a save button.

> Do you want any kind of feedback to the user that it has saved?

I think for now we don't need this, but we may follow up at some point and implement some kind of growl or toast to confirm the selection.

**Comment by anthony-hull** [comment] 2021-02-22 18:44
Thanks Shawn. I worked on that assumption over the weekend, so that's how it currently works 👍 

I still would like input on how the picker should work on iOS please 🙏

**Comment by marcaaron** [comment] 2021-02-22 19:47
>I ran into an issue with iOS that the picker library takes up a lot more space than in the designs and works differently to s drop down. Please look on the project page at the iOS and PickerIOS screenshots.

Can you maybe explain what the issue is here exactly with some screenshots?

>I found an alternative:
https://github.com/lawnstarter/react-native-picker-select
which wraps the RN team's picker library in a modal and gives you freedom to style the elements in the page. This would allow the styling and layout of the settings page to be more consistent across platforms. (it is also more popular)

I'm a little unclear on what the differences are and it looks like they have about the same amount of downloads. Expo is using the one I recommended, but I don't have any particular strong feelings one way or the other. It looks like the library you are recommending is written in 100% JS. Does that mean that it does not take advantage of the native picker on iOS?

It would be good to see the options and then have @shawnborton weigh in on how it all should work. I don't have a preference here and could go either way.

**Comment by anthony-hull** [comment] 2021-02-22 20:40
react-native-picker-select implements { Picker } from '@react-native-picker/picker' directly. It provides some wrapping behaviour like putting the iOS picker in a modal. Otherwise the picker, inline, without that looks like my video (except would take up more space if I styled it to not to break its box): 
https://user-images.githubusercontent.com/47184118/108766634-4fff6000-754d-11eb-863d-cb975a009cd6.mp4

With that library it would behave more like this:
![image](https://github.com/lawnstarter/react-native-picker-select/raw/master/ex-ios.gif)

**Comment by marcaaron** [comment] 2021-02-22 21:34
Ok cool thanks. I believe the second one is what we want to go with so let's use `react-native-picker-select`.

**Comment by anthony-hull** [comment] 2021-02-23 01:57
this brings me back to the issue I had when I tested out the library. When I first build the app after installing I get this:
`
ERROR in ./node_modules/react-native-picker-select/src/index.js 9:21
Module parse failed: Unexpected token (9:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class RNPickerSelect extends PureComponent {
>     static propTypes = {
|         onValueChange: PropTypes.func.isRequired,
|         items: PropTypes.arrayOf(
 @ ./src/pages/SettingsPage.js 4:0-56 104:91-105
 @ ./src/pages/home/HomePage.js
 @ ./src/Expensify.js
 @ ./src/App.js
 @ ./index.js
`
Looking at the structure of your webpack file and the different excludes etc I'm hoping you guys have experience with issues like this. I can see there are regexes in the webpack based on platform file names for controlling when babel loader. This library implements everything in one single file with a bunch of it statements in the render function:
https://github.com/lawnstarter/react-native-picker-select/blob/ca6488c2eef5c776a8071400c8b7987712d43397/src/index.js#L556-L573
Which I would be missed by these regexes.

What do you think?

**Comment by marcaaron** [comment] 2021-02-23 02:19
This seems fairly common with the react native libraries. They work fine in metro then break on web (even if they have web support). webpack thinks there's a syntax error because it's not being transpiled correctly so I _think_ we just have to add the library name here:

https://github.com/Expensify/Expensify.cash/blob/f0411611cd667b6d6ccd7f5b11fcb72475c51b07/config/webpack/webpack.common.js#L63

If that doesn't work I'd look at the babel config next to see if there's something we need to add.

**Comment by anthony-hull** [comment] 2021-02-23 02:26
I tried that too. But It shifts the error to react native picker actual
when this library imports it. I'll post the error tomorrow. Any ideas for
me to look at in Babel tomorrow?

**Comment by marcaaron** [comment] 2021-02-23 02:30
Maybe better to push what you have and I can help take a look.

**Comment by anthony-hull** [comment] 2021-02-23 02:36
https://github.com/anthony-hull/Expensify.cash/tree/anthony-1452-add-GSD-mode-to-sidebar here is my WIP commit for moving to the new library

**Comment by marcaaron** [comment] 2021-02-23 02:36
Also looks like this might be a known issue https://github.com/react-native-picker/picker/issues/82#issuecomment-747578526

**Comment by anthony-hull** [comment] 2021-02-23 02:45
Nice find. Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jag96** [comment] 2021-03-02 22:08
Added a comment on [the linked PR](https://github.com/Expensify/Expensify.cash/pull/1553#issuecomment-789253972) regarding a bug, reopening this

**Comment by Jag96** [comment] 2021-03-10 00:00
The second PR was merged, closing this!

**Closed by Jag96** 2021-03-10 00:00 UTC
Labels: Exported
