### ISSUE TITLE
Android - Emoji - Cursor is not in front of the emoji

### ISSUE THREAD

**Issue by isagoico** [Expensify/Expensify.cash#3186] opened 2021-05-27 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result
Cursor position should display in front of the emoji 

## Actual Result
Cursor position is not in front of the emoji. Sometimes is behind the emoji and sometimes 2 characters ahead. 

## Action Performed
1. Launch the app
2. Log in with any account
3. Type some text
4. Add emoji in the middle of text

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.55-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:**

![image](https://user-images.githubusercontent.com/44479856/119721520-37972e00-be39-11eb-96a6-daf160176b34.png)

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
Originally posted here: https://github.com/Expensify/Expensify.cash/pull/3080#issuecomment-849069503

**Comment by isagoico** [comment] 2021-05-27 17:06
CC @aliabbasmalik8

**Comment by nickmurray47** [comment] 2021-05-27 18:09
Going to unassign myself and set it as weekly given that there's an easy workaround on Android by just using the native emoji picker. @aliabbasmalik8 brought up what the issue is in this comment [here](https://github.com/Expensify/Expensify.cash/pull/3080#issuecomment-849303436).

**Comment by isagoico** [comment] 2021-05-31 00:02
Issue reproducible today during KI retests

**Comment by aliabbasmalik8** [comment] 2021-05-31 23:13
**SOLUTION**
It can be fixed by adding 
```
this.textInput.setNativeProps({selection: updatedSelection});
```
at here 
https://github.com/Expensify/Expensify.cash/blob/e95f5a3d07408794e8055b955f1a5666a9508e0c/src/pages/home/report/ReportActionCompose.js#L288

Actually `selection props` have some serious problem with native platforms  you can see on this link
`github.com/facebook/react-native/issues/29063`

REF: https://reactnative.dev/docs/direct-manipulation#:~:text=It%20is%20sometimes%20necessary%20to,for%20views%20in%20mobile%20apps.

Thanks

**Comment by jboniface** [comment] 2021-06-03 18:56
@aliabbasmalik8 this should be fixed as part of https://github.com/Expensify/Expensify.cash/pull/3080 -- all fixes submitted should resolve the issue for all platforms. In your PR you flagged that you tested Android but it was not addressed in your fix.

**Comment by aliabbasmalik8** [comment] 2021-06-03 19:12
@jboniface yeah, I'm on it, just want to discuss the solution for this issue because `selection` has some issue on android.
yes, I tested on Android as well but it did not produce every time on android so that's the reason it missed.

**Comment by isagoico** [comment] 2021-06-07 01:21
Issue reproducible today during KI retests

**Closed** 2021-06-08 18:39 UTC
Labels: Engineering, Weekly
