### ISSUE TITLE
Inconsistent Android back button behavior while navigated to a modal view

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/Expensify.cash#2066] opened 2021-03-25 00:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Expected Result:
The Android hardware back button should work when pressed.

## Actual Result:
When you open the settings page the first back button press is ignored (as if an extra invisible page was added to the page stack), but the second and third back button press work as expected. 

## Action Performed:
1. Open the settings modal
2. Press the back button 

## Platform: 
Android

**Notes/Photos/Videos:** 

- This issue is caused by a bug in `react-navigation` and must be fixed in that repo first. 
- **See:** https://github.com/react-navigation/react-navigation/issues/9364
- Workarounds will not be accepted.

**Expensify/Expensify Issue URL:**
https://github.com/Expensify/Expensify/issues/157248
**Upwork link:** https://www.upwork.com/jobs/~016d2a711284ef2fc7

**Comment by sohaibkhaa** [comment] 2021-03-25 10:48
I will fix the issue by manipulating the app behaviour and debugging to check whether is there any other page opened while opening the settings page. After finding the bug try to resolve it by updating the part of code that is used to open up settings page. And debug the back press behaviour of settings page.

**Comment by ahmedahtazaz** [comment] 2021-03-25 19:14
While reviewing through the job I have noticed that there is no custom hardware back button handling in your app. Well in my experience it is a must for Android. This is a normal issue while building cross-platform apps with React Native because the developer is mostly focused on one platform and expect it to work on both of them.

**Comment by parasharrajat** [comment] 2021-03-25 19:24
@ahmedahtazaz  Don't you think react-navigation gives that by default?

**Comment by ahmedahtazaz** [comment] 2021-03-25 19:30
So in my point of view custom back button handling is needed in these scenarios.

**Comment by kaushiktd** [comment] 2021-03-26 16:45
Hi,

This is Kaushik here and here is explanation for this,

1.  Maybe a configuration issue in the stack, will be resolved by stack management or manage back handler on a specific page on the single back

**Comment by marcaaron** [comment] 2021-03-29 16:05
@ahmedahtazaz I'm not too sure what the exact proposal is here yet. Can you briefly outline the changes you intend to make and point to some specific area in the code?

**Comment by ahmedahtazaz** [comment] 2021-03-29 18:47
@marcaaron I have attached a screenshot that points to the point in code where I will add a custom back button handler. This handler will receive all the back button press events. I will check the routes here and if the current route is settings/preferences i will executes this function: Navigation.navigate(ROUTES.SETTINGS)Navigation.navigate(ROUTES.SETTINGS)

In this way the back button handling will be delegated to the PreferencesPage instead of HeaderWithCloseButton.

I hope my solution is clear now. 
![Screenshot 2021-03-29 at 11 34 14 PM](https://user-images.githubusercontent.com/49054500/112884555-117b3900-90e9-11eb-9afb-45d40547fff2.png)

**Comment by marcaaron** [comment] 2021-03-29 19:41
It's still unclear to me sorry. The [docs](https://reactnavigation.org/docs/custom-android-back-button-handling/) state:

>By default, when user presses the Android hardware back button, react-navigation will pop a screen or exit the app if there are no screens to pop. This is a sensible default behavior, but there are situations when you might want to implement custom handling.

If the "sensible default behavior" is that a back button press should return us to the last place we were (which in this case should dismiss the settings screen and display the side bar again).

**But the issue states:**

>When you open the settings page the first back button press is ignored

So, I don't see how the custom back button handler helps us here. Why is the first back button press ignored?

**Comment by marcaaron** [comment] 2021-03-29 19:53
Looked into this a bit and surely this is the bug here...

https://github.com/react-navigation/react-navigation/issues/9364

Ideally, this would get fixed in the react-navigation library. But I think we'll need to implement this same solution in all screens. So if we implement the work around it should happen in the `ScreenWrapper` component and we should link to that issue so it can be fixed by upgrading eventually.

**Comment by ahmedahtazaz** [comment] 2021-03-29 19:55
@marcaaron here is the catch. When I will add a custom back button handler the first hardware back press will give me the actual route or the actual current route in the navigation stack. Then we will have a very good understanding if there is a screen on top of the preferences screen or not. Custom back handling will be used as a debugging strategy here as well.

**Comment by ahmedahtazaz** [comment] 2021-03-29 19:57
@marcaaron as a matter of fact I did not know about this bug react-navigation/react-navigation#9364. 

Thanks for this information. Yes implementation of custom back handler in ScreenWrapper will be generic and will fix this issue in all screens where this wrapper is being used.

**Comment by ahmedahtazaz** [comment] 2021-03-29 19:59
Please let me know if I should start working on this or if you are delegating it to someone else.

**Comment by ahmedahtazaz** [comment] 2021-03-29 20:08
@marcaaron  One another thing we will add custom back handler in ScreenWrapper but will only use this handling for those where the problem occurs. I think this problem is not consistent across all screens so we will only do this for setting/preferences route. If there are more problematic routes later in app development then we will add those routes with time in this handling.

There is also a style guideline ambiguity here as well ScreenWrapper is functional component and we will have to use hooks here now or we should convert it to class based component if we are avoiding hooks.

Kindly clear these questions as well before we proceed.

**Comment by marcaaron** [comment] 2021-03-29 21:32
In this case, the most correct solution seems to be to submit a fix PR to `react-navigation` repo and solve this bug by updating to the latest version.

**Comment by marcaaron** [comment] 2021-03-29 21:32
If that doesn't work, we can return to discuss this workaround some more.

**Comment by ahmedahtazaz** [comment] 2021-03-29 21:38
Okay.

**Comment by marcaaron** [comment] 2021-04-02 01:20
Alright, so I've looked into this issue some more and I don't think it's something that will be fixed in `react-navigation` any time soon ([more context here](https://github.com/react-navigation/react-navigation/issues/9364#issuecomment-812253690)). The default behavior of the drawer navigator is to close the drawer when the back button is pressed and it doesn't take into account screens that are rendered modally above it in a stack navigator.

Based on all that, I think the custom back handler is our best bet to solve this problem.

Building on your initial proposal @ahmedahtazaz we should...

1. Create a `ModalScreenWrapper` component for all screens that are presenting modally. It should wrap the screen `ScreenWrapper` component and capture the back handler handles like you've mentioned not allowing them to fall to the `DrawerView` (see my comments on the react-nav issue).
2. We will just call `navigation.goBack()` when the back button is pressed.
3. Pressing the back button while we are in a nested route like `settings/password` should bring us back to the previous view.
4. Deep links should be able to navigate back to the open drawer with a back button press

As for hooks, if we can avoid them that would be best.

**Comment by marcaaron** [comment] 2021-04-02 01:21
@ahmedahtazaz @trjExpensify I think we're good to go here.

**Comment by ahmedahtazaz** [comment] 2021-04-02 13:25
@marcaaron kindly accept my upwork proposal so that we can start on this.

**Comment by trjExpensify** [comment] 2021-04-02 15:42
Yep, done! 👍 Please make sure to link your PR to this issue and drop a comment when you're ready.

**Comment by ahmedahtazaz** [comment] 2021-04-02 17:16
@trjExpensify I have accepted your offer and starting my work on this.

**Comment by marcaaron** [comment] 2021-04-02 18:13
Sorry everyone. So this is an interesting development, but I _think_ this change here will actually make the proposal no longer necessary.

https://github.com/react-navigation/react-navigation/commit/5ae0badc44b576d464f8841822a911b18a698403

Maybe we should hold until it's published?

**Comment by ahmedahtazaz** [comment] 2021-04-02 18:24
@marcaaron @trjExpensify totally up to you. I have no issues with waiting on.

**Comment by trjExpensify** [comment] 2021-04-02 19:00
Cool, down to hold. Let's check back in shortly!

**Comment by marcaaron** [comment] 2021-04-06 18:38
I verified the issue has been fixed and published so we need only bump the `@react-navigation/drawer` version to `5.12.5` and then test the outcome.

https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fdrawer%405.12.5

**Comment by ahmedahtazaz** [comment] 2021-04-06 18:42
@marcaaron @trjExpensify okay. So should I withdraw my proposal now or upgrade @react-navigation/drawer version to 5.12.5 and test it?

**Comment by marcaaron** [comment] 2021-04-06 18:47
>upgrade @react-navigation/drawer version to 5.12.5 and test it

Let's start with this since it's very easy to do. I'm hopeful that it will resolve this issue. Thanks.

**Comment by ahmedahtazaz** [comment] 2021-04-06 18:48
okay.

**Comment by ahmedahtazaz** [comment] 2021-04-06 20:32
@marcaaron i think this upgrade is going to open new issues because upgrade of @react-navigation/drawer version to 5.12.5 requires react-native version upgrade to 0.64.0 and react upgrade to 17.0.1.

**Comment by marcaaron** [comment] 2021-04-06 20:55
What about this change requires upgrading those other dependencies?

**Comment by ahmedahtazaz** [comment] 2021-04-06 21:01
@marcaaron in @react-navigation/drawer 5.12.5 react-native version 0.64.0 has been added as peer dependancy. So we got to have the sam react-native version in our dependancies.

**Comment by ahmedahtazaz** [comment] 2021-04-06 21:03
i think this is the reference commit which has upgraded this dependancy https://github.com/react-navigation/react-navigation/commit/9fce3a433c312a0e69e633e9d1c04fc9c0a8d645. This was released in version 5.12.5 of @react-navigation/drawer.

**Comment by marcaaron** [comment] 2021-04-06 22:47
Sorry, can you maybe explain what problems we are going to run into if we upgrade to `@react-navigation/drawer 5.12.5` without upgrading our version of `react-native`?

**Comment by ahmedahtazaz** [comment] 2021-04-07 17:48
![Screenshot 2021-04-07 at 10 43 43 PM](https://user-images.githubusercontent.com/49054500/113910999-e7193200-97f2-11eb-84dc-dab6315e1057.png)

@marcaaron it means that we cannot upgrade to @react-navigation/drawer 5.12.5 because our project has a different version of react-native and @react-navigation/drawer 5.12.5 is compatible with or requires a different version of react-native. We need to resolve this conflict to upgrade @react-navigation/drawer.

**Comment by ahmedahtazaz** [comment] 2021-04-07 17:49
I hope you have got my point now.

**Comment by parasharrajat** [comment] 2021-04-07 17:54
@ahmedahtazaz Have you tried the `--force` switch command? I think the above comment is saying to list down the issues that you face after installing it forcefully with old react-native.

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:09
@parasharrajat yes force upgrading this dependancy is a way of doing this. But in this case we will have to perform a full testing cycle on this app to be sure about all the issues which we might face. 

I think this full testing is not in the scope of this issue. So I will try to force upgrade the dependancy and share my results which are related to this issue.

**Comment by marcaaron** [comment] 2021-04-07 18:21
Not sure what we are doing to get this error to appear, but I updated only this package in `package.json` then did an `npm install` without any issues.

**Comment by marcaaron** [comment] 2021-04-07 18:25
We have a QA team that can test this change for any regressions and do a full test cycle. But some reasonable testing of back button behaviors is expected and should be scoped to this issue, no?

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:31
@marcaaron yes a reasonable testing of back button is in the scope of this issue and i will do that.

As far simple npm install is concerned by just upgrading the dependancy version to 5.12.5 I am sharing the screenshot in which I am doing the same but with same error appearing.
![Screenshot 2021-04-07 at 11 27 30 PM](https://user-images.githubusercontent.com/49054500/113916136-0e72fd80-97f9-11eb-8a13-e7b5b0a277cc.png)

If you want me to force upgrade this dependancy then let me know, i will do that and share my findings as discussed with @parasharrajat

**Comment by marcaaron** [comment] 2021-04-07 18:36
Ok, I don't see the issues you're seeing at all on my end. Not sure what the explanation for that would be.

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:38
@marcaaron can you share your package.json file?

**Comment by parasharrajat** [comment] 2021-04-07 18:38
Difference between npm CLI versions.

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:39
@parasharrajat yeah may be but if there are conflicts in the dependancy tree than any npm cli version will throw the error. right?

**Comment by parasharrajat** [comment] 2021-04-07 18:45
I think you can try `npm ci`. Not an expert though. :smile:

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:48
@parasharrajat we can try npm install with --force as well. But we are having a conflict on npm install. Btw I am trying with latest npm version that is 7.8.0

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:51
@marcaaron i think we should figure this out as soon as possible. Kindly let me know if you want me to force upgrade it or not.

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:53
@parasharrajat can you do us a favour here and just try to update @react-navigation/drawer version to 5.12.5 and run npm install?

**Comment by ahmedahtazaz** [comment] 2021-04-07 18:53
just to be sure

**Comment by parasharrajat** [comment] 2021-04-07 18:56
Had to say. No errors on my side. I am using npm 6.14.11

**Comment by ahmedahtazaz** [comment] 2021-04-07 19:04
@parasharrajat seems like an npm cli version issue. Some reference issues https://github.com/npm/cli/issues/2000 and https://github.com/npm/cli/issues/2119.

**Comment by ahmedahtazaz** [comment] 2021-04-07 20:17
@marcaaron after version update of @react-navigation/drawer to 5.12.5 issue still persists.

**Comment by ahmedahtazaz** [comment] 2021-04-07 20:19
First hardware back press on settings page is still not working.

**Comment by marcaaron** [comment] 2021-04-07 20:50
Have you tried to reset the JS cache in metro? I've tested the change on physical Android device and emulator and the issue seems to be resolved. Hard to say what issues you're running into. Can you open a PR?

**Comment by ahmedahtazaz** [comment] 2021-04-07 21:14
@marcaaron yes I have reset the JS cache of metro bundler. Opened up a PR https://github.com/Expensify/Expensify.cash/pull/2281

**Closed** 2021-04-09 17:51 UTC
Labels: Exported
