### ISSUE TITLE
Android - Profile - Blank page is displayed when accessing profile settings

### ISSUE THREAD

**Issue by isagoico** [Expensify/Expensify.cash#2253] opened 2021-04-07 01:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Profile page opens with settings details

## Actual Result:
Empty screen opens

## Action Performed:
1. Launch the app and login
2. Tap avatar
3. Tap profile

## Workaround:
No workaround found to access the profile in Android app 

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.13-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
Issue not reproducible in production. 

<img src="https://user-images.githubusercontent.com/44479856/113795869-dea1f800-971b-11eb-8879-332d4f220860.png" width="40%">

https://user-images.githubusercontent.com/44479856/113795916-f5484f00-971b-11eb-812d-f9eff15d9e38.mp4

**Expensify/Expensify Issue URL:**

**Comment by marcaaron** [comment] 2021-04-07 03:05
This is a duplicate of https://github.com/Expensify/Expensify/issues/158699

**Comment by isagoico** [comment] 2021-04-07 03:28
@marcaaron this is also happening for older accounts, so not sure if it's still a dup. All accounts old and new are being affected by this.

**Comment by isagoico** [comment] 2021-04-07 16:11
Looks like this was fixed! 🎉 

<img src="https://user-images.githubusercontent.com/44479856/113898823-35e6ad80-979a-11eb-93c0-691b32fa8668.png" width="40%">

CC @NikkiWines

**Closed** 2021-04-07 16:11 UTC
Labels: DeployBlockerCash
