### ISSUE TITLE
Blocks of `quoted` text render incorrectly on mobile

### ISSUE THREAD

**Issue by jboniface** [Expensify/Expensify.cash#986] opened 2020-12-16 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~01fc428a62f97f17a2).

**Platform - version:**  

iOS and Android, build 263

**Action Performed (reproducible steps):**

1. Type a sentence with code block formatting (single ticks) in the middle, like this:

This is a test to `see how code renders in the middle` of a sentence on mobile.

2. Notice that it renders strangely by either breaking the line or overflowing.

**Expected Result:**

It should render the same way it does here on GitHub.

This is a test to `see how code renders in the middle` of a sentence on mobile.

**Actual Result:**

The line either breaks or overflows where the code formatting starts/ends

**Notes/Photos/Videos:** 

We've seen multiple results from this bug. Here are some examples:

![101217023-6e804a00-3635-11eb-9bb9-2e37a0eeccbb](https://user-images.githubusercontent.com/24399930/102400316-bf862b80-3faf-11eb-9680-c66d16210de5.png)

![102281699-4c22f080-3f94-11eb-878b-345b9d978e46](https://user-images.githubusercontent.com/24399930/102400335-c6ad3980-3faf-11eb-8d74-ffa6e2f57719.jpg)

**Comment by sakul-budhathoki** [comment] 2020-12-30 16:12
PR https://github.com/Expensify/Expensify.cash/pull/1099

**Comment by telesensdev** [comment] 2021-01-04 07:49
I worked with this bug

**Comment by laurenreidexpensify** [comment] 2021-01-04 14:42
@telesensdev can you clarify what the name you have registered in Upwork is? Thanks

**Comment by telesensdev** [comment] 2021-01-04 15:17
@laurenreidexpensify upwork account - Eduard Rubin

**Comment by tugbadogan** [comment] 2021-02-24 22:39
Hi @jboniface, is this task still available? It looks like there isn't any activity for a while.

**Comment by jboniface** [comment] 2021-02-25 14:06
@tugbadogan we're not quite sure how to solve it optimally, and another contributor put up a PR that we weren't able to move forward with because it wasn't consistent across platforms. Do you have a proposal that would resolve this issue?

**Comment by mallenexpensify** [comment] 2021-03-24 17:31
Reposted this on Upwork https://www.upwork.com/jobs/~01fc428a62f97f17a2
Please create new comments for proposals, even if you're already commented above

**Comment by mallenexpensify** [comment] 2021-03-24 17:35
@tgolen assigning to you to review incoming proposals because you were picked via auto-assigner for the issue in the Expensify repo

**Comment by aliabbasmalik8** [comment] 2021-03-24 19:37
@sketchydroide is it okay?
for ios
![image](https://user-images.githubusercontent.com/31027036/112372570-e1dac400-8cd7-11eb-94a2-94a82276afc1.png)

![image](https://user-images.githubusercontent.com/31027036/112372623-ee5f1c80-8cd7-11eb-9c07-600870ba4f40.png)

and for web
![image](https://user-images.githubusercontent.com/31027036/112372847-37af6c00-8cd8-11eb-84b4-1604a3e60005.png)

**Comment by sketchydroide** [comment] 2021-03-25 18:45
> @sketchydroide is it okay?
> for ios 

I think for iOS we are expect the text to be on the same line as the rest of the text. It's wrapping well, and going to the next line correctly, but it also should be on the same line of the rest of the text, not on a new line.
Web looks good

Does that make sense @aliabbasmalik8

**Comment by sketchydroide** [comment] 2021-04-05 12:48
@aliabbasmalik8 Do you think you could do the changes as I described them?

**Comment by aliabbasmalik8** [comment] 2021-04-06 17:54
@sketchydroide did not found a solution according to the changes you described above.
There is two solution 
1. https://github.com/Expensify/Expensify.cash/issues/986#issuecomment-806109447
2. inline text but without border and padding properties.

BLOCKER: Not found any way to assign border and padding properties to `<Text>` element without using `<View>` if you have an idea how to do this please let me know.

Thanks

**Comment by sakul-budhathoki** [comment] 2021-04-07 07:47
> @sketchydroide did not found a solution according to the changes you described above.
> There is two solution
> 
> 1. [#986 (comment)](https://github.com/Expensify/Expensify.cash/issues/986#issuecomment-806109447)
> 2. inline text but without border and padding properties.
> 
> BLOCKER: Not found any way to assign border and padding properties to `<Text>` element without using `<View>` if you have an idea how to do this please let me know.
> 
> Thanks



> @sketchydroide did not found a solution according to the changes you described above.
> There is two solution
> 
> 1. [#986 (comment)](https://github.com/Expensify/Expensify.cash/issues/986#issuecomment-806109447)
> 2. inline text but without border and padding properties.
> 
> BLOCKER: Not found any way to assign border and padding properties to `<Text>` element without using `<View>` if you have an idea how to do this please let me know.
> 
> Thanks

Hi @sketchydroide, @aliabbasmalik8 . There is some limitation to fix this issue completely. I have sent PR some time before https://github.com/Expensify/Expensify.cash/pull/1099. React native has styling limitation with <Text> inside <Text>. Inner <Text> will not obey some styles.

**Comment by parasharrajat** [comment] 2021-04-07 14:57
@sketchydroide I think this issue is hanging around for a long time. I tried few techniques that could let us achieve the desired UI.

## Problem
We tried using a combination of `Text` & `View` tag to achieve the above UI but there are a couple of issues as follows:
1. Text is rendered as a block box but we want inline text.
2. In Another way, we can get the inline text but border and `border-radius` are not being rendered. 

## Solution
I had an idea of tokenizing the text. Then apply the style selectively. This is working well. I have made a small snap [here](https://snack.expo.io/@rajat_parashar/text-wrapping).
1. we created one wrapper component which divides the text into tokens(words) divided based on word break. This component put the text tokens inline into a view and renders it.
2. We can then pass styles selectively to tokens and manage the `border-radius` for the first and last tokens.

**Comment by sketchydroide** [comment] 2021-04-08 10:24
@parasharrajat I think that might work, would be happy to see a PR using this

**Comment by mallenexpensify** [comment] 2021-04-13 18:11
Hired @parasharrajat in Upwork

**Closed** 2021-04-20 23:51 UTC
Labels: Exported

**Comment by mallenexpensify** [comment] 2021-04-23 17:28
This closed 3 days ago, waiting til 4/27 to ensure no regressions then paying

**Comment by mallenexpensify** [comment] 2021-04-28 20:55
Paid 4/28 via Upwork.  Thanks @parasharrajat

**Comment by parasharrajat** [comment] 2021-04-28 23:59
@mallenexpensify but PR is awaiting merge https://github.com/Expensify/Expensify.cash/pull/2527.
