### ISSUE TITLE
External contributor instructions don't work for web on Windows

### ISSUE THREAD

**Issue by dylmye** [Expensify/Expensify.cash#1083] opened 2020-12-23 22:32 UTC
Hi, I've followed the instructions in your README [here](https://github.com/Expensify/Expensify.cash#running-the-apps-via-production-api-proxy-contributors-) and have set everything up fresh. When I run `npm run proxy` I see this in CLI:
```
> expensify.cash@1.0.1-292 proxy ...\Expensify.cash
> node proxy.js & webpack-dev-server --open --config config/webpack/webpack.dev.js --env.proxy=true

Proxy server listening at http://localhost:9000
```

Navigating to `http://localhost:9000` redirects me to expensify.com. I've followed all the steps (though if I'm supposed to set up ngrok, the linked stackoverflow is private)

Please let me know how to set up the project as an external contributor. Thank you :)

(PS: on Windows 10, Firefox and Edge Chromium)

**Comment by dylmye** [comment] 2020-12-23 22:46
If I try to run `npm run web` instead, I get this error:
![image](https://user-images.githubusercontent.com/7024578/103041757-40749280-456f-11eb-803b-468664800a54.png)
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (global.js:20)
    at Module../node_modules/webpack/buildin/global.js (app-9843bb43b85a977c7960.bundle.js:189676)
```

**Comment by dylmye** [comment] 2020-12-24 21:19
Thanks, just saw the updated README today.
I've copied the latest production env file and switch use_web_proxy to true.

The page I get redirected to now is https://www.expensify.com/?exitTo=inbox&email=

**Comment by laurenreidexpensify** [comment] 2020-12-30 14:17
@dylmye thanks for creating this proactively! are you sorted or is this still an issue for you?

**Comment by henryrossiter** [comment] 2020-12-30 23:03
This is an issue for me as well.

**Comment by dylmye** [comment] 2020-12-31 00:53
Hi @laurenreidexpensify, I'm still having this issue on the latest version of master.

**Comment by dylmye** [comment] 2020-12-31 01:17
Related issue: #1125

**Comment by henryrossiter** [comment] 2020-12-31 18:58
#1144 Solves this issue on my end.

**Comment by laurenreidexpensify** [comment] 2021-01-29 13:15
Hey @dylmye 

Can you confirm - 
- That the error is still occurring 
- whether you have a proposed solution for fixing it?

Thanks!

**Comment by marcaaron** [comment] 2021-03-31 20:22
Going to close this since there hasn't been much activity.

**Closed by marcaaron** 2021-03-31 20:22 UTC

**Comment by kidroca** [comment] 2021-04-01 15:33
I'm getting the same error. The change to ` babel.config.js` here #1144 fixes this for me too

Though you can add it like:
```js
const webpack = {
    sourceType: 'unambiguous',

    env: {
        production: {
            presets: defaultPresets,
            plugins: [...defaultPlugins, 'transform-remove-console'],
        },
        development: {
            presets: defaultPresets,
            plugins: defaultPlugins,
        },
    },
};
```

I'm not sure what exactly causes this but looks like it's related to babel config in the root of the project - everything using babel internally might use it - I think webpack-dev-server uses it to compile stuff (it's socket client) internally

I don't have this problem for other projects where I'm using an earlier version of webpack and webpack-dev-server

Updating webback-dev-server didn't solve this

**Comment by kidroca** [comment] 2021-05-21 22:38
To start the dev web server on windows edit the `package.json` like so:

```json
    "web-server": "webpack-dev-server --open --config config/webpack/webpack.dev.js",
    "web-proxy": "node web/proxy.js",
```

And start the two processes separately on different terminals
1. first `npm run web-proxy` in one terminal
2. then `npm run web` in the other


The changes to `sourceType: 'unambiguous',` are also required under windows 

I keep these changes in a separate stash and use them locally being careful not to commit them

---

The problem is under windows you can't use `&` to start processes in parallel
There are npm packages that solve this like https://www.npmjs.com/package/concurrently

```json
   "web": "concurrently \"npm:web-proxy\" \"npm:web-server\""
   "web-server": "webpack-dev-server --open --config config/webpack/webpack.dev.js",
   "web-proxy": "node web/proxy.js",
```

**Comment by hiteshagja** [comment] 2022-01-20 08:53
![image](https://user-images.githubusercontent.com/5493716/150305271-7f352948-a800-4580-af1d-c7d3e06ae3cb.png)

end up with this error.
